name: CI Pipeline

on: [push, pull_request]

jobs:
  install_dependencies:
    runs-on: ubuntu-latest
    outputs:
      node_modules: ${{ steps.install_dependencies.outputs.node_modules }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@kjartanik'
          always-auth: true

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with: 
          bun-version: "latest"
        
      - name: Install dependencies with Bun
        id: install_dependencies
        run: bun install

      - name: Install dependencies with npm
        run: npm install
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  typecheck:
    runs-on: ubuntu-latest
    needs: install_dependencies
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with: 
          bun-version: "latest"

      - name: Install dependencies with Bun
        run: bun install
        
      - name: Typecheck
        run: bun tsc

  test:
    runs-on: ubuntu-latest
    needs: install_dependencies
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with: 
          bun-version: "latest"

      - name: Install dependencies with Bun
        run: bun install

      - name: Run tests with coverage
        run: bun run test --coverage

      - name: Upload coverage report
        uses: actions/upload-artifact@v4 
        with:
          name: coverage-report
          path: coverage

  publish:
    runs-on: ubuntu-latest
    needs: install_dependencies
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with: 
          bun-version: "latest"

      - name: Install dependencies with Bun
        run: bun install

      - name: Bump package version
        run: npm version patch --no-git-tag-version

      - name: Setup npm auth
        run: |
          echo "@kjartanik:registry=https://npm.pkg.github.com/" > .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc

      - name: Publish package to GitHub Packages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm publish
