name: Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Bun
      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      # Typecheck with TypeScript
      - name: TypeScript Typecheck
        run: bun tsc

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Bun
      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      # Install dependencies
      - name: Install dependencies
        run: bun install

      # Run tests
      - name: Run tests with npm
        run: npm run test -- --coverage

      # Upload coverage report to coverage folder
      - name: Save coverage report
        run: mkdir -p coverage && mv ./coverage/* coverage/

      # Upload coverage to github
      - name: Upload coverage to GitHub
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: ./coverage

  publish:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Bun
      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      # Set up npm authentication for GitHub
      - name: Setup npm auth
        run: |
          echo "@$kjartanik:registry=https://npm.pkg.github.com/" > .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc

      # Log in to GitHub Packages
      - name: Log in to GitHub Packages
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> ~/.npmrc

      # Publish to GitHub Packages
      - name: Publish package to GitHub Packages
        run: bun publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
