name: Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Bun
      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      
      - name: Install dependencies
        run: bun install

      # Typecheck with TypeScript
      - name: TypeScript Typecheck
        run: bun tsc

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Bun
      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      # Install dependencies
      - name: Install dependencies
        run: bun install

      # Run tests
      - name: Run tests with npm
        run: npm run test -- --coverage

      # Upload coverage to github
      - name: Upload coverage to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: ./coverage

  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@kik_code'
          always-auth: true

      - name: Check npm authentication
        run: npm whoami --registry=https://npm.pkg.github.com/
        env:
          NPM_TOKEN: ${{ secrets.NPM_SECRET }}

      - name: Publish to GitHub Packages
        run: npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_SECRET }}

